export global Icons {
    out property <image> folder: @image-url("../icons/folder-8x8.png");
    out property <image> empty: @image-url("../icons/empty-8x8.png");

    out property <image> saving: @image-url("../icons/saving-8x8.png");

    out property <image> left-caret: @image-url("../icons/left-caret.png");
    out property <image> right-caret: @image-url("../icons/right-caret.png");
    out property <image> right-arrow: @image-url("../icons/right-arrow.png");

    out property <image> btn-a: @image-url("../icons/btn-a-12x12.png");
    out property <image> btn-b: @image-url("../icons/btn-b-12x12.png");
    out property <image> btn-x: @image-url("../icons/btn-x-12x12.png");
    out property <image> btn-home: @image-url("../icons/btn-home-12x12.png");
    out property <image> btn-dpad-down: @image-url("../icons/btn-dpad-down-12x12.png");
}
