import { Backend } from "../common.slint";
import { Icons } from "../icons.slint";

export component Notification inherits Rectangle {
    in property <string> text;

    width: self.min-width;
    height: self.min-height;
    background: white;
    border-color: black;
    border-radius: 4px;
    border-width: 1px;

    HorizontalLayout {
        padding: 4px;
        spacing: 4px;

        Image {
            source: Icons.folder;
            colorize: #333;
        }

        Text {
            color: black;
            text: text;
            vertical-alignment: center;
        }
    }
}
